### ISSUE TITLE
Vercel死んでませんか

### ISSUE THREAD

**Issue by SnO2WMaN** [iamtakagi/spotify2image#5]
私用のScrapboxでそれなりに使っているので、面倒でしたら引き継ぎします

**Comment by r130919** [comment]
@SnO2WMaN 
Redeploy しましたが、こんな感じです・・・

![image](https://user-images.githubusercontent.com/46530214/162429927-6b038c9e-44d2-48c6-a4a1-995e82b9413d.png)

**Comment by r130919** [comment]
> 私用のScrapboxでそれなりに使っているので、面倒でしたら引き継ぎします

@SnO2WMaN
このリポジトリは Archive して (Vercel の方も削除するので)、そちらのリポジトリで同ドメイン引き継ぎしてもらって構いません

**Comment by SnO2WMaN** [comment]
個人から個人への引き継ぎってありませんでしたっけ？

**Comment by SnO2WMaN** [comment]
無いのか　ではそれでお願いします　ありがとうございました

**Comment by r130919** [comment]
個人引き継ぎ的な機能、あったかもしれません。もう消してしまいました・・・

引き継ぎお願いします、ありがとうございました。
